version: '3.8'
services:
  mysql:
    image: "mysql:8.0.26"
    platform: linux/x86_64
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - "./data:/var/lib/mysql"
    env_file:
      - "./mysql.env"
  flask:
    build:
      context: .
    volumes:
      - "/var/run/python:/var/run/python"
    restart: unless-stopped
